name: 'Auto Sync Repos'
author: yixinglu
description: 'Sync two repos by creating pull request automatically'
inputs:
  from_repo:
    description: 'from repository to current'
    required: true
  repo_token:
    description: 'repository token to access the codebase'
    required: true
  dingtalk_access_token:
    description: 'dingtalk access token'
    required: false
    default: ''
  dingtalk_secret:
    description: 'dingtalk secret'
    required: false
    default: ''
runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: 'refresh-cw'
  color: 'yellow'
